// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4r7Vuz7D-hQXWsLLL92ZNEssTP3ZXqv4',
    appId: '1:194619597829:android:e52ba9dc50541833f2286c',
    messagingSenderId: '194619597829',
    projectId: 'engine-4a21e',
    databaseURL: 'https://engine-4a21e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'engine-4a21e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT9nV8dEc2ii0gE58Rqc7BSbQI7lWmJzc',
    appId: '1:194619597829:ios:cac423bbb0ea4f2af2286c',
    messagingSenderId: '194619597829',
    projectId: 'engine-4a21e',
    databaseURL: 'https://engine-4a21e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'engine-4a21e.appspot.com',
    iosBundleId: 'com.engine.step',
  );
}
